$(document).ready(function(){

	$('#btnSearch').click(function(){
		googleSearch();
		return false;
	});

	function googleSearch(settings){

		$.post('/search', {'query': $('#txbInput').val()}, function(r){

			var results = JSON.parse(r).result[0].docIndex;

			$('#resultsDiv').empty();

			if(results && results.length){

				// If results were returned, add them to a pageContainer div,
				// after which append them to the #resultsDiv:

				var pageContainer = $('<div>',{className:'pageContainer'});

				for(var i=0;i<results.length;i++){
					// Creating a new result object and firing its toString method:
					pageContainer.append(new result(results[i]) + '');
				}

				pageContainer.append('<div class="clear"></div>')
							 .hide().appendTo(resultsDiv)
							 .fadeIn('slow');
			}
			else {
				$('<p>',{className:'notFound',html:'No Results Were Found!'}).hide().appendTo($('#resultsDiv')).fadeIn();
			}
		});
	}

	function result(r){

		// This is class definition. Object of this class are created for
		// each result. The markup is generated by the .toString() method.

		var arr = [];

		var json = r.id[0].json

		arr = [
			'<li>',
			'<h6><a href="', json.url,'">', json.name,'</a></h6>',
			'<a href="', json.area.url, '" class="result-url">', json.area.name, '</a>',
			'<a href="', json.employer.url, '" class="result-url">', json.employer.name, '</a>',
			'<p><strong>Требования: </strong>', json.snippet.requirement,'</p>',
			'<p><strong>Обязанности: </strong>', json.snippet.responsibility,'</p>',
			'<p><strong>Зарплата: </strong>', json.salary.from, '-', json.salary.to, '</p>',
			'</li>'
		];
		this.toString = function(){
			return arr.join('');
		}
	}
});
